name = "PartonDensity"
uuid = "2526459f-0e84-440c-98d6-63172703d9a4"
authors = ["Francesca Capel <capel.francesca@gmail.com> and contributors"]
version = "0.1.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DensityInterface = "b429d917-457f-4dbc-8f4c-0cc954292b1d"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
NaNMath = "77ba4419-2d1f-58cd-9bb1-8ffee604a2e3"
ParallelProcessingTools = "8e8a01fc-6193-5ca1-a2f1-20776dae4199"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
ValueShapes = "136a8f8c-c49b-4edb-8b98-f3d64d48be8f"

[compat]
CSV = "0.8, 0.9, 0.10"
Distributions = "0.24, 0.25"
HDF5 = "0.16"
NaNMath = "0.3, 1"
ParallelProcessingTools = "0.4"
Parameters = "0.12"
Plots = "1"
Roots = "1"
SpecialFunctions = "1, 2"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
